/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => QuizDexPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/security/CredentialManager.ts
var import_obsidian = require("obsidian");
var _CredentialManager = class _CredentialManager {
  // 15 minutes
  constructor(plugin) {
    this.plugin = plugin;
    this.masterKey = null;
    this.keyCache = /* @__PURE__ */ new Map();
    this.CACHE_TTL = 15 * 60 * 1e3;
  }
  /**
   * Initialize the credential manager with a master passphrase
   * This passphrase is NEVER stored - only used to derive encryption keys
   */
  async initialize(passphrase) {
    if (!passphrase) {
      return await this.initializeOpenMode();
    }
    try {
      const stored = await this.getStoredCredentials();
      if (stored.keyHash) {
        const isValid = await this.verifyPassphrase(passphrase, stored.keyHash);
        if (!isValid) {
          new import_obsidian.Notice("\u274C Invalid passphrase");
          return false;
        }
      }
      this.masterKey = await this.deriveMasterKey(passphrase);
      return true;
    } catch (error) {
      console.error("Failed to initialize credential manager:", error);
      new import_obsidian.Notice("\u274C Failed to initialize secure storage");
      return false;
    }
  }
  /**
   * Initialize in open mode (legacy compatibility - NOT RECOMMENDED)
   * Shows prominent warning to user
   */
  async initializeOpenMode() {
    new import_obsidian.Notice("\u26A0\uFE0F WARNING: API keys stored in PLAINTEXT. Enable encryption in settings!", 1e4);
    console.warn("QuizDex: Running in INSECURE mode - API keys not encrypted");
    return true;
  }
  /**
   * Store an API key securely with encryption
   */
  async setCredential(provider, apiKey, passphrase) {
    try {
      if (!passphrase && !this.masterKey) {
        return await this.setCredentialInsecure(provider, apiKey);
      }
      const key = passphrase ? await this.deriveMasterKey(passphrase) : this.masterKey;
      if (!key) {
        throw new Error("No encryption key available");
      }
      const salt = crypto.getRandomValues(new Uint8Array(16));
      const iv = crypto.getRandomValues(new Uint8Array(12));
      const encoder = new TextEncoder();
      const data = encoder.encode(apiKey);
      const encryptedData = await crypto.subtle.encrypt(
        { name: "AES-GCM", iv },
        key,
        data.buffer
      );
      const stored = await this.getStoredCredentials();
      const encryptedCredential = {
        provider,
        encryptedKey: this.arrayBufferToBase64(encryptedData),
        iv: this.arrayBufferToBase64(iv.buffer),
        salt: this.arrayBufferToBase64(salt.buffer),
        iterations: _CredentialManager.ITERATIONS,
        timestamp: Date.now()
      };
      const index = stored.credentials.findIndex((c) => c.provider === provider);
      if (index >= 0) {
        stored.credentials[index] = encryptedCredential;
      } else {
        stored.credentials.push(encryptedCredential);
      }
      if (!stored.keyHash && passphrase) {
        stored.keyHash = await this.hashPassphrase(passphrase);
      }
      await this.saveStoredCredentials(stored);
      this.keyCache.delete(provider);
      new import_obsidian.Notice(`\u2705 API key for ${provider} encrypted and saved`);
      return true;
    } catch (error) {
      console.error("Failed to set credential:", error);
      new import_obsidian.Notice(`\u274C Failed to save API key for ${provider}`);
      return false;
    }
  }
  /**
   * Retrieve and decrypt an API key
   * Caches decrypted key in memory for TTL duration
   */
  async getCredential(provider) {
    try {
      const cached = this.keyCache.get(provider);
      if (cached && cached.expires > Date.now()) {
        return cached.key;
      }
      if (this.masterKey) {
        const stored = await this.getStoredCredentials();
        const credential = stored.credentials.find((c) => c.provider === provider);
        if (credential) {
          const decrypted = await this.decryptCredential(credential);
          this.keyCache.set(provider, {
            key: decrypted,
            expires: Date.now() + this.CACHE_TTL
          });
          return decrypted;
        }
      }
      return await this.getCredentialInsecure(provider);
    } catch (error) {
      console.error("Failed to get credential:", error);
      return null;
    }
  }
  /**
   * Decrypt a credential using the master key
   */
  async decryptCredential(credential) {
    if (!this.masterKey) {
      throw new Error("No master key available");
    }
    const encryptedData = this.base64ToArrayBuffer(credential.encryptedKey);
    const iv = this.base64ToArrayBuffer(credential.iv);
    const decryptedData = await crypto.subtle.decrypt(
      { name: "AES-GCM", iv },
      this.masterKey,
      encryptedData
    );
    const decoder = new TextDecoder();
    return decoder.decode(decryptedData);
  }
  /**
   * Remove a credential
   */
  async removeCredential(provider) {
    try {
      const stored = await this.getStoredCredentials();
      stored.credentials = stored.credentials.filter((c) => c.provider !== provider);
      await this.saveStoredCredentials(stored);
      this.keyCache.delete(provider);
      new import_obsidian.Notice(`\u2705 API key for ${provider} removed`);
      return true;
    } catch (error) {
      console.error("Failed to remove credential:", error);
      return false;
    }
  }
  /**
   * Check if a credential exists (without decrypting)
   */
  async hasCredential(provider) {
    const stored = await this.getStoredCredentials();
    const hasEncrypted = stored.credentials.some((c) => c.provider === provider);
    if (hasEncrypted)
      return true;
    return await this.hasCredentialInsecure(provider);
  }
  /**
   * List all providers that have credentials
   */
  async listProviders() {
    const stored = await this.getStoredCredentials();
    return stored.credentials.map((c) => c.provider);
  }
  /**
   * Clear all credentials and memory cache
   */
  async clearAll() {
    await this.saveStoredCredentials({ version: 1, credentials: [] });
    this.keyCache.clear();
    this.masterKey = null;
    new import_obsidian.Notice("\u2705 All credentials cleared");
  }
  /**
   * Migrate from plaintext to encrypted storage
   */
  async migrateToEncrypted(passphrase, plaintextSettings) {
    try {
      await this.initialize(passphrase);
      const providers = [
        { key: "openAIApiKey", provider: "openai" },
        { key: "googleApiKey", provider: "google" },
        { key: "anthropicApiKey", provider: "anthropic" },
        { key: "perplexityApiKey", provider: "perplexity" },
        { key: "mistralApiKey", provider: "mistral" },
        { key: "cohereApiKey", provider: "cohere" }
      ];
      let migratedCount = 0;
      for (const { key, provider } of providers) {
        const apiKey = plaintextSettings[key];
        if (apiKey && apiKey.trim()) {
          await this.setCredential(provider, apiKey, passphrase);
          migratedCount++;
        }
      }
      new import_obsidian.Notice(`\u2705 Migrated ${migratedCount} API keys to encrypted storage`);
      return true;
    } catch (error) {
      console.error("Migration failed:", error);
      new import_obsidian.Notice("\u274C Failed to migrate API keys");
      return false;
    }
  }
  /**
   * Derive encryption key from passphrase using PBKDF2
   */
  async deriveMasterKey(passphrase, salt) {
    const encoder = new TextEncoder();
    const passphraseKey = await crypto.subtle.importKey(
      "raw",
      encoder.encode(passphrase),
      "PBKDF2",
      false,
      ["deriveBits", "deriveKey"]
    );
    const actualSalt = salt ? salt : crypto.getRandomValues(new Uint8Array(16));
    return await crypto.subtle.deriveKey(
      {
        name: "PBKDF2",
        salt: actualSalt,
        iterations: _CredentialManager.ITERATIONS,
        hash: "SHA-256"
      },
      passphraseKey,
      { name: "AES-GCM", length: _CredentialManager.KEY_SIZE },
      false,
      ["encrypt", "decrypt"]
    );
  }
  /**
   * Hash passphrase for verification (NOT for encryption)
   */
  async hashPassphrase(passphrase) {
    const encoder = new TextEncoder();
    const data = encoder.encode(passphrase);
    const hash = await crypto.subtle.digest("SHA-256", data);
    return this.arrayBufferToBase64(hash);
  }
  /**
   * Verify passphrase against stored hash
   */
  async verifyPassphrase(passphrase, storedHash) {
    const hash = await this.hashPassphrase(passphrase);
    return hash === storedHash;
  }
  // === LEGACY INSECURE STORAGE (for backward compatibility) ===
  async setCredentialInsecure(provider, apiKey) {
    const settings = await this.plugin.loadData() || {};
    const keyMap = {
      "openai": "openAIApiKey",
      "google": "googleApiKey",
      "anthropic": "anthropicApiKey",
      "perplexity": "perplexityApiKey",
      "mistral": "mistralApiKey",
      "cohere": "cohereApiKey"
    };
    const settingKey = keyMap[provider];
    if (settingKey) {
      settings[settingKey] = apiKey;
      await this.plugin.saveData(settings);
      return true;
    }
    return false;
  }
  async getCredentialInsecure(provider) {
    const settings = await this.plugin.loadData() || {};
    const keyMap = {
      "openai": "openAIApiKey",
      "google": "googleApiKey",
      "anthropic": "anthropicApiKey",
      "perplexity": "perplexityApiKey",
      "mistral": "mistralApiKey",
      "cohere": "cohereApiKey"
    };
    const settingKey = keyMap[provider];
    return settingKey ? settings[settingKey] || null : null;
  }
  async hasCredentialInsecure(provider) {
    const key = await this.getCredentialInsecure(provider);
    return key !== null && key.trim().length > 0;
  }
  // === STORAGE HELPERS ===
  async getStoredCredentials() {
    const data = await this.plugin.loadData() || {};
    return data[_CredentialManager.STORAGE_KEY] || { version: 1, credentials: [] };
  }
  async saveStoredCredentials(store) {
    const data = await this.plugin.loadData() || {};
    data[_CredentialManager.STORAGE_KEY] = store;
    await this.plugin.saveData(data);
  }
  // === ENCODING HELPERS ===
  arrayBufferToBase64(buffer) {
    const bytes = new Uint8Array(buffer);
    let binary = "";
    for (let i = 0; i < bytes.byteLength; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    return btoa(binary);
  }
  base64ToArrayBuffer(base64) {
    const binary = atob(base64);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) {
      bytes[i] = binary.charCodeAt(i);
    }
    return bytes.buffer;
  }
  /**
   * Security audit - check for insecure keys
   */
  async auditSecurity() {
    const stored = await this.getStoredCredentials();
    const secure = stored.credentials.length;
    const settings = await this.plugin.loadData() || {};
    const insecureKeys = [
      "openAIApiKey",
      "googleApiKey",
      "anthropicApiKey",
      "perplexityApiKey",
      "mistralApiKey",
      "cohereApiKey"
    ];
    const insecure = insecureKeys.filter((key) => settings[key] && settings[key].trim()).length;
    return {
      secure,
      insecure,
      providers: stored.credentials.map((c) => c.provider)
    };
  }
  /**
   * Clean up on plugin unload
   */
  destroy() {
    this.keyCache.clear();
    this.masterKey = null;
  }
};
_CredentialManager.ITERATIONS = 1e5;
// PBKDF2 iterations
_CredentialManager.KEY_SIZE = 256;
// AES-256
_CredentialManager.STORAGE_KEY = "encrypted_credentials";
var CredentialManager = _CredentialManager;

// src/services/AIProviderOrchestrator.ts
var import_obsidian2 = require("obsidian");
var AIProviderOrchestrator = class {
  constructor() {
    this.providers = /* @__PURE__ */ new Map();
    this.circuitBreakers = /* @__PURE__ */ new Map();
    // Circuit breaker configuration
    this.FAILURE_THRESHOLD = 3;
    this.RESET_TIMEOUT = 6e4;
  }
  // 1 minute
  /**
   * Register an AI provider
   */
  registerProvider(provider) {
    this.providers.set(provider.name, provider);
    this.circuitBreakers.set(provider.name, {
      failures: 0,
      lastFailure: 0,
      state: "closed"
    });
    console.log(`\u2705 Registered AI provider: ${provider.displayName}`);
  }
  /**
   * Get a specific provider
   */
  getProvider(name) {
    return this.providers.get(name);
  }
  /**
   * List all registered provider names
   */
  listProviders() {
    return Array.from(this.providers.keys());
  }
  /**
   * Generate quiz with automatic fallback
   */
  async generateQuizWithFallback(noteContents, options, preferredProvider) {
    const startTime = Date.now();
    const providerOrder = this.determineProviderOrder(preferredProvider);
    let lastError;
    let totalAttempts = 0;
    for (const providerName of providerOrder) {
      const provider = this.providers.get(providerName);
      if (!provider)
        continue;
      if (!this.canUseProvider(providerName)) {
        console.warn(`\u26A0\uFE0F Circuit breaker OPEN for ${providerName}, skipping`);
        continue;
      }
      console.log(`\u{1F504} Attempting quiz generation with ${provider.displayName}...`);
      try {
        const quiz = await this.generateWithRetry(
          provider,
          noteContents,
          options
        );
        this.recordSuccess(providerName);
        const duration2 = Date.now() - startTime;
        console.log(`\u2705 Quiz generated successfully with ${provider.displayName} in ${duration2}ms`);
        return {
          success: true,
          quiz,
          provider: providerName,
          attemptCount: totalAttempts + 1,
          duration: duration2
        };
      } catch (error) {
        totalAttempts++;
        const providerError = this.normalizeError(error, providerName);
        lastError = providerError;
        this.recordFailure(providerName);
        console.error(`\u274C ${provider.displayName} failed:`, providerError.message);
        if (!provider.isRetryableError(providerError)) {
          console.warn(`\u26A0\uFE0F Non-retryable error from ${providerName}, stopping fallback`);
          break;
        }
      }
    }
    const duration = Date.now() - startTime;
    const errorMessage = lastError ? `All providers failed. Last error: ${lastError.message}` : "No available AI providers";
    new import_obsidian2.Notice(`\u274C ${errorMessage}`);
    return {
      success: false,
      error: lastError || {
        code: "UNKNOWN_ERROR" /* UNKNOWN_ERROR */,
        message: errorMessage,
        provider: "none",
        retryable: false
      },
      provider: "none",
      attemptCount: totalAttempts,
      duration
    };
  }
  /**
   * Generate quiz with retry logic for a single provider
   */
  async generateWithRetry(provider, noteContents, options, maxRetries = 3) {
    let lastError;
    for (let attempt = 0; attempt < maxRetries; attempt++) {
      try {
        const quiz = await this.withTimeout(
          provider.generateQuiz(noteContents, options),
          options.timeout || 6e4
          // Default 60s timeout
        );
        return quiz;
      } catch (error) {
        lastError = error;
        console.warn(`Attempt ${attempt + 1}/${maxRetries} failed for ${provider.name}`);
        if (attempt < maxRetries - 1) {
          const delay = provider.getRetryDelay(attempt);
          console.log(`\u23F3 Waiting ${delay}ms before retry...`);
          await this.sleep(delay);
        }
      }
    }
    throw lastError || new Error("Max retries exceeded");
  }
  /**
   * Timeout wrapper for promises
   */
  async withTimeout(promise, timeoutMs) {
    return Promise.race([
      promise,
      new Promise(
        (_, reject) => setTimeout(() => reject(new Error(`Timeout after ${timeoutMs}ms`)), timeoutMs)
      )
    ]);
  }
  /**
   * Determine provider order (preferred first, then others)
   */
  determineProviderOrder(preferredProvider) {
    const allProviders = Array.from(this.providers.keys());
    if (!preferredProvider || !this.providers.has(preferredProvider)) {
      return allProviders;
    }
    return [
      preferredProvider,
      ...allProviders.filter((p) => p !== preferredProvider)
    ];
  }
  /**
   * Circuit breaker - check if provider can be used
   */
  canUseProvider(providerName) {
    const breaker = this.circuitBreakers.get(providerName);
    if (!breaker)
      return true;
    const now = Date.now();
    switch (breaker.state) {
      case "closed":
        return true;
      case "open":
        if (now - breaker.lastFailure > this.RESET_TIMEOUT) {
          breaker.state = "half-open";
          console.log(`\u{1F504} Circuit breaker HALF-OPEN for ${providerName}`);
          return true;
        }
        return false;
      case "half-open":
        return true;
    }
  }
  /**
   * Record successful provider call
   */
  recordSuccess(providerName) {
    const breaker = this.circuitBreakers.get(providerName);
    if (!breaker)
      return;
    breaker.failures = 0;
    breaker.state = "closed";
  }
  /**
   * Record failed provider call
   */
  recordFailure(providerName) {
    const breaker = this.circuitBreakers.get(providerName);
    if (!breaker)
      return;
    breaker.failures++;
    breaker.lastFailure = Date.now();
    if (breaker.failures >= this.FAILURE_THRESHOLD) {
      breaker.state = "open";
      console.warn(`\u26A0\uFE0F Circuit breaker OPENED for ${providerName} after ${breaker.failures} failures`);
      new import_obsidian2.Notice(`\u26A0\uFE0F ${providerName} temporarily disabled due to errors`);
    }
  }
  /**
   * Normalize various error types into AIProviderError
   */
  normalizeError(error, provider) {
    var _a, _b, _c;
    if (error.code && error.message && error.provider) {
      return error;
    }
    if ((_a = error.message) == null ? void 0 : _a.includes("Timeout")) {
      return {
        code: "TIMEOUT" /* TIMEOUT */,
        message: "Request timed out",
        provider,
        retryable: true
      };
    }
    if (((_b = error.message) == null ? void 0 : _b.includes("fetch")) || ((_c = error.message) == null ? void 0 : _c.includes("network"))) {
      return {
        code: "NETWORK_ERROR" /* NETWORK_ERROR */,
        message: error.message || "Network error occurred",
        provider,
        retryable: true
      };
    }
    if (error.statusCode) {
      return this.httpStatusToError(error.statusCode, provider, error.message);
    }
    return {
      code: "UNKNOWN_ERROR" /* UNKNOWN_ERROR */,
      message: error.message || "Unknown error occurred",
      provider,
      retryable: false
    };
  }
  /**
   * Convert HTTP status codes to error codes
   */
  httpStatusToError(statusCode, provider, message) {
    if (statusCode === 401) {
      return {
        code: "INVALID_API_KEY" /* INVALID_API_KEY */,
        message: message || "Invalid API key",
        provider,
        retryable: false,
        statusCode
      };
    }
    if (statusCode === 403) {
      return {
        code: "FORBIDDEN" /* FORBIDDEN */,
        message: message || "Access forbidden",
        provider,
        retryable: false,
        statusCode
      };
    }
    if (statusCode === 429) {
      return {
        code: "RATE_LIMIT_EXCEEDED" /* RATE_LIMIT_EXCEEDED */,
        message: message || "Rate limit exceeded",
        provider,
        retryable: true,
        statusCode
      };
    }
    if (statusCode === 404) {
      return {
        code: "MODEL_NOT_FOUND" /* MODEL_NOT_FOUND */,
        message: message || "Model not found",
        provider,
        retryable: false,
        statusCode
      };
    }
    if (statusCode >= 500) {
      return {
        code: "PROVIDER_ERROR" /* PROVIDER_ERROR */,
        message: message || "Provider server error",
        provider,
        retryable: true,
        statusCode
      };
    }
    return {
      code: "UNKNOWN_ERROR" /* UNKNOWN_ERROR */,
      message: message || `HTTP ${statusCode}`,
      provider,
      retryable: statusCode >= 500,
      statusCode
    };
  }
  /**
   * Test all providers and return health status
   */
  async testAllProviders() {
    const results = /* @__PURE__ */ new Map();
    for (const [name, provider] of this.providers) {
      try {
        const healthy = await provider.testConnection();
        results.set(name, healthy);
      } catch (error) {
        console.error(`Failed to test provider ${name}:`, error);
        results.set(name, false);
      }
    }
    return results;
  }
  /**
   * Get circuit breaker status for all providers
   */
  getCircuitBreakerStatus() {
    return new Map(this.circuitBreakers);
  }
  /**
   * Manually reset a circuit breaker
   */
  resetCircuitBreaker(providerName) {
    const breaker = this.circuitBreakers.get(providerName);
    if (breaker) {
      breaker.failures = 0;
      breaker.state = "closed";
      console.log(`\u{1F504} Circuit breaker RESET for ${providerName}`);
    }
  }
  /**
   * Sleep utility
   */
  sleep(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }
  /**
   * Clean up resources
   */
  destroy() {
    this.providers.clear();
    this.circuitBreakers.clear();
  }
};

// src/services/providers/OllamaProvider.ts
var import_obsidian3 = require("obsidian");
var OllamaProvider = class {
  constructor() {
    this.name = "ollama";
    this.displayName = "Ollama (Local)";
    this.config = null;
  }
  async initialize(config) {
    this.config = config;
    console.log(`\u2705 Ollama provider initialized: ${config.baseURL}`);
  }
  async testConnection() {
    if (!this.config)
      return false;
    try {
      const baseEndpoint = this.config.baseURL.replace(/\/$/, "");
      const response = await (0, import_obsidian3.requestUrl)({
        url: `${baseEndpoint}/api/tags`,
        method: "GET",
        throw: false
      });
      return response.status === 200;
    } catch (error) {
      console.error("Ollama connection test failed:", error);
      return false;
    }
  }
  async getAvailableModels() {
    if (!this.config)
      return [];
    try {
      const baseEndpoint = this.config.baseURL.replace(/\/$/, "");
      const response = await (0, import_obsidian3.requestUrl)({
        url: `${baseEndpoint}/api/tags`,
        method: "GET"
      });
      if (response.status === 200) {
        const data = response.json;
        if (data.models && Array.isArray(data.models)) {
          return data.models.map((model) => model.name || model.model || "").filter((name) => name.length > 0);
        }
      }
      return [];
    } catch (error) {
      console.error("Failed to fetch Ollama models:", error);
      return [];
    }
  }
  async generateQuiz(noteContents, options) {
    if (!this.config) {
      throw this.createError(
        "PROVIDER_ERROR" /* PROVIDER_ERROR */,
        "Ollama provider not initialized"
      );
    }
    const combinedContent = noteContents.join("\n\n---\n\n");
    const prompt = this.buildPrompt(
      combinedContent,
      options.questionCount,
      options.difficulty,
      options.includeMultipleChoice,
      options.includeTrueFalse
    );
    const modelToUse = await this.validateModelName(
      options.modelOverride || this.config.model
    );
    try {
      const baseEndpoint = this.config.baseURL.replace(/\/$/, "");
      const response = await (0, import_obsidian3.requestUrl)({
        url: `${baseEndpoint}/api/generate`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          model: modelToUse,
          prompt,
          stream: false,
          options: {
            temperature: 0.7,
            top_p: 0.9
          }
        })
      });
      if (response.status !== 200) {
        throw this.createError(
          "PROVIDER_ERROR" /* PROVIDER_ERROR */,
          `Ollama API error: ${response.status}`,
          response.status
        );
      }
      const result = response.json;
      if (!result || !result.response) {
        throw this.createError(
          "INVALID_RESPONSE" /* INVALID_RESPONSE */,
          "Invalid response format from Ollama"
        );
      }
      return this.parseQuizResponse(result.response, options);
    } catch (error) {
      if (error.provider) {
        throw error;
      }
      throw this.createError(
        "PROVIDER_ERROR" /* PROVIDER_ERROR */,
        error.message || "Failed to generate quiz"
      );
    }
  }
  async validateModelName(modelName) {
    try {
      const availableModels = await this.getAvailableModels();
      if (availableModels.includes(modelName)) {
        return modelName;
      }
      const matchingModel = availableModels.find(
        (model) => model.startsWith(modelName + ":") || model === modelName
      );
      if (matchingModel) {
        console.log(`Model name corrected: ${modelName} -> ${matchingModel}`);
        return matchingModel;
      }
      const baseModelName = modelName.split(":")[0];
      const baseMatchingModel = availableModels.find(
        (model) => model.split(":")[0] === baseModelName
      );
      if (baseMatchingModel) {
        console.log(`Model name corrected: ${modelName} -> ${baseMatchingModel}`);
        return baseMatchingModel;
      }
      console.warn(`Model '${modelName}' not found. Available:`, availableModels);
      return modelName;
    } catch (error) {
      console.error("Failed to validate model name:", error);
      return modelName;
    }
  }
  isRetryableError(error) {
    return error.retryable && error.code !== "INVALID_API_KEY" /* INVALID_API_KEY */;
  }
  getRetryDelay(attemptNumber) {
    return Math.min(1e3 * Math.pow(2, attemptNumber), 1e4);
  }
  async healthCheck() {
    const startTime = Date.now();
    const isHealthy = await this.testConnection();
    const latency = Date.now() - startTime;
    return {
      healthy: isHealthy,
      latency,
      message: isHealthy ? "Ollama server responding" : "Ollama server unreachable"
    };
  }
  // === PRIVATE HELPERS ===
  buildPrompt(content, questionCount, difficulty, includeMultipleChoice, includeTrueFalse) {
    const questionTypes = [];
    if (includeMultipleChoice) {
      questionTypes.push("Multiple Choice: Provide 4 options (A, B, C, D) with only one correct answer.");
    }
    if (includeTrueFalse) {
      questionTypes.push("True/False: Provide a statement that is either true or false.");
    }
    const typeInstructions = questionTypes.join(" ");
    return `You are an expert quiz generator. Based on the following study material, create ${questionCount} ${difficulty} level questions.

QUESTION TYPES TO INCLUDE: ${typeInstructions}

STUDY MATERIAL:
${content}

INSTRUCTIONS:
1. Create exactly ${questionCount} questions total
2. Mix the question types as requested
3. Questions should be ${difficulty} level
4. Focus on key concepts, facts, and understanding
5. Provide clear explanations for correct answers

REQUIRED OUTPUT FORMAT (JSON):
{
  "title": "Quiz Title",
  "description": "Brief description of quiz content",
  "questions": [
    {
      "id": "q1",
      "type": "multiple-choice",
      "question": "What is...?",
      "options": ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
      "correctAnswer": "A",
      "explanation": "Explanation of why this is correct"
    },
    {
      "id": "q2",
      "type": "true-false",
      "question": "Statement to evaluate",
      "correctAnswer": "true",
      "explanation": "Explanation"
    }
  ]
}

Generate the quiz now:`;
  }
  parseQuizResponse(response, options) {
    try {
      const jsonMatch = response.match(/\{[\s\S]*\}/);
      if (!jsonMatch) {
        throw this.createError(
          "PARSING_ERROR" /* PARSING_ERROR */,
          "No JSON found in response"
        );
      }
      const quizData = JSON.parse(jsonMatch[0]);
      return {
        id: this.generateId(),
        title: quizData.title || "Generated Quiz",
        description: quizData.description || "AI-generated quiz from your notes",
        questions: quizData.questions.map((q, index) => ({
          id: q.id || `q${index + 1}`,
          type: q.type,
          question: q.question,
          options: q.options || void 0,
          correctAnswer: q.correctAnswer,
          explanation: q.explanation || void 0
        })),
        createdAt: /* @__PURE__ */ new Date(),
        sourceNotes: options.selectedNotes.map((note) => note.basename || note.name)
      };
    } catch (error) {
      console.error("Failed to parse quiz response:", error);
      console.error("Raw response:", response);
      throw this.createError(
        "PARSING_ERROR" /* PARSING_ERROR */,
        "Failed to parse AI response. Please try again."
      );
    }
  }
  generateId() {
    return Date.now().toString(36) + Math.random().toString(36).substr(2);
  }
  createError(code, message, statusCode) {
    return {
      code,
      message,
      provider: this.name,
      retryable: this.isErrorCodeRetryable(code),
      statusCode
    };
  }
  isErrorCodeRetryable(code) {
    const retryableCodes = [
      "TIMEOUT" /* TIMEOUT */,
      "NETWORK_ERROR" /* NETWORK_ERROR */,
      "RATE_LIMIT_EXCEEDED" /* RATE_LIMIT_EXCEEDED */,
      "PROVIDER_ERROR" /* PROVIDER_ERROR */
    ];
    return retryableCodes.includes(code);
  }
};

// src/services/providers/OpenAIProvider.ts
var import_obsidian4 = require("obsidian");
var OpenAIProvider = class {
  constructor() {
    this.name = "openai";
    this.displayName = "OpenAI";
    this.config = null;
  }
  async initialize(config) {
    this.config = config;
  }
  async testConnection() {
    if (!this.config || !this.config.apiKey)
      return false;
    try {
      const response = await (0, import_obsidian4.requestUrl)({
        url: `${this.config.baseURL}/models`,
        method: "GET",
        headers: {
          "Authorization": `Bearer ${this.config.apiKey}`
        },
        throw: false
      });
      return response.status === 200;
    } catch (error) {
      return false;
    }
  }
  async getAvailableModels() {
    if (!this.config || !this.config.apiKey)
      return [];
    try {
      const response = await (0, import_obsidian4.requestUrl)({
        url: `${this.config.baseURL}/models`,
        method: "GET",
        headers: {
          "Authorization": `Bearer ${this.config.apiKey}`
        }
      });
      if (response.status === 200) {
        const data = response.json;
        return data.data.filter((model) => model.id.includes("gpt")).map((model) => model.id);
      }
      return [];
    } catch (error) {
      return [];
    }
  }
  async generateQuiz(noteContents, options) {
    var _a, _b;
    if (!this.config || !this.config.apiKey) {
      throw this.createError("INVALID_API_KEY" /* INVALID_API_KEY */, "OpenAI API key not configured");
    }
    const combinedContent = noteContents.join("\n\n---\n\n");
    const prompt = this.buildPrompt(combinedContent, options);
    try {
      const response = await (0, import_obsidian4.requestUrl)({
        url: `${this.config.baseURL}/chat/completions`,
        method: "POST",
        headers: {
          "Authorization": `Bearer ${this.config.apiKey}`,
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          model: options.modelOverride || this.config.model,
          messages: [
            { role: "system", content: "You are an expert quiz generator. Generate quizzes in JSON format." },
            { role: "user", content: prompt }
          ],
          temperature: 0.7,
          response_format: { type: "json_object" }
        })
      });
      if (response.status !== 200) {
        throw this.createError(
          this.statusToErrorCode(response.status),
          `OpenAI API error: ${response.status}`,
          response.status
        );
      }
      const result = response.json;
      if (!result.choices || !((_b = (_a = result.choices[0]) == null ? void 0 : _a.message) == null ? void 0 : _b.content)) {
        throw this.createError("INVALID_RESPONSE" /* INVALID_RESPONSE */, "Invalid response from OpenAI");
      }
      return this.parseQuizResponse(result.choices[0].message.content, options);
    } catch (error) {
      if (error.provider)
        throw error;
      throw this.createError("PROVIDER_ERROR" /* PROVIDER_ERROR */, error.message || "OpenAI request failed");
    }
  }
  async validateModelName(modelName) {
    const availableModels = await this.getAvailableModels();
    if (availableModels.includes(modelName)) {
      return modelName;
    }
    return modelName;
  }
  isRetryableError(error) {
    return error.retryable && error.code !== "INVALID_API_KEY" /* INVALID_API_KEY */;
  }
  getRetryDelay(attemptNumber) {
    return Math.min(1e3 * Math.pow(2, attemptNumber), 1e4);
  }
  async healthCheck() {
    const startTime = Date.now();
    const isHealthy = await this.testConnection();
    const latency = Date.now() - startTime;
    return {
      healthy: isHealthy,
      latency,
      message: isHealthy ? "OpenAI API responding" : "OpenAI API unreachable"
    };
  }
  buildPrompt(content, options) {
    const questionTypes = [];
    if (options.includeMultipleChoice) {
      questionTypes.push("multiple-choice");
    }
    if (options.includeTrueFalse) {
      questionTypes.push("true-false");
    }
    return `Generate a quiz with ${options.questionCount} questions at ${options.difficulty} difficulty level.

Question types: ${questionTypes.join(", ")}

Study material:
${content}

Return ONLY valid JSON in this exact format:
{
  "title": "Quiz Title",
  "description": "Brief description",
  "questions": [
    {
      "id": "q1",
      "type": "multiple-choice",
      "question": "Question text?",
      "options": ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
      "correctAnswer": "A",
      "explanation": "Why this is correct"
    }
  ]
}`;
  }
  parseQuizResponse(content, options) {
    try {
      const quizData = JSON.parse(content);
      return {
        id: this.generateId(),
        title: quizData.title || "Generated Quiz",
        description: quizData.description || "AI-generated quiz",
        questions: quizData.questions.map((q, index) => ({
          id: q.id || `q${index + 1}`,
          type: q.type,
          question: q.question,
          options: q.options,
          correctAnswer: q.correctAnswer,
          explanation: q.explanation
        })),
        createdAt: /* @__PURE__ */ new Date(),
        sourceNotes: options.selectedNotes.map((note) => note.basename || note.name)
      };
    } catch (error) {
      throw this.createError("PARSING_ERROR" /* PARSING_ERROR */, "Failed to parse OpenAI response");
    }
  }
  generateId() {
    return Date.now().toString(36) + Math.random().toString(36).substr(2);
  }
  statusToErrorCode(status) {
    if (status === 401)
      return "INVALID_API_KEY" /* INVALID_API_KEY */;
    if (status === 429)
      return "RATE_LIMIT_EXCEEDED" /* RATE_LIMIT_EXCEEDED */;
    if (status === 404)
      return "MODEL_NOT_FOUND" /* MODEL_NOT_FOUND */;
    if (status >= 500)
      return "PROVIDER_ERROR" /* PROVIDER_ERROR */;
    return "UNKNOWN_ERROR" /* UNKNOWN_ERROR */;
  }
  createError(code, message, statusCode) {
    return {
      code,
      message,
      provider: this.name,
      retryable: this.isErrorCodeRetryable(code),
      statusCode
    };
  }
  isErrorCodeRetryable(code) {
    const retryableCodes = [
      "TIMEOUT" /* TIMEOUT */,
      "NETWORK_ERROR" /* NETWORK_ERROR */,
      "RATE_LIMIT_EXCEEDED" /* RATE_LIMIT_EXCEEDED */,
      "PROVIDER_ERROR" /* PROVIDER_ERROR */
    ];
    return retryableCodes.includes(code);
  }
};

// src/services/ProviderFactory.ts
var ProviderFactory = class {
  /**
   * Initialize all providers and register them with the orchestrator
   */
  static async initializeAll(orchestrator, getConfig) {
    const ollamaConfig = await getConfig("ollama");
    if (ollamaConfig) {
      const ollamaProvider = new OllamaProvider();
      await ollamaProvider.initialize(ollamaConfig);
      orchestrator.registerProvider(ollamaProvider);
    }
    const openaiConfig = await getConfig("openai");
    if (openaiConfig && openaiConfig.apiKey) {
      const openaiProvider = new OpenAIProvider();
      await openaiProvider.initialize(openaiConfig);
      orchestrator.registerProvider(openaiProvider);
    }
  }
  /**
   * Get list of all supported provider names
   */
  static getSupportedProviders() {
    return [
      "ollama",
      "openai",
      "anthropic",
      "google",
      "perplexity",
      "mistral",
      "cohere"
    ];
  }
  /**
   * Get display name for a provider
   */
  static getProviderDisplayName(provider) {
    const displayNames = {
      "ollama": "Ollama (Local)",
      "openai": "OpenAI",
      "anthropic": "Anthropic",
      "google": "Google AI",
      "perplexity": "Perplexity",
      "mistral": "Mistral AI",
      "cohere": "Cohere"
    };
    return displayNames[provider] || provider;
  }
  /**
   * Check if provider requires API key
   */
  static requiresApiKey(provider) {
    return provider !== "ollama";
  }
};

// src/ui/PassphraseModal.ts
var import_obsidian5 = require("obsidian");
var PassphraseModal = class extends import_obsidian5.Modal {
  constructor(app, onSubmit, isNewPassphrase = false) {
    super(app);
    this.passphrase = "";
    this.confirmPassphrase = "";
    this.onSubmit = onSubmit;
    this.isNewPassphrase = isNewPassphrase;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u{1F510} Encryption Passphrase" });
    if (this.isNewPassphrase) {
      contentEl.createDiv({
        text: "Create a passphrase to encrypt your API keys. Keep it safe - you'll need it to access your keys!",
        cls: "setting-item-description"
      }).style.marginBottom = "20px";
    } else {
      contentEl.createDiv({
        text: "Enter your passphrase to unlock encrypted API keys.",
        cls: "setting-item-description"
      }).style.marginBottom = "20px";
    }
    new import_obsidian5.Setting(contentEl).setName("Passphrase").setDesc(this.isNewPassphrase ? "Minimum 8 characters (12+ recommended)" : "Enter your passphrase").addText((text) => {
      text.setPlaceholder("Enter passphrase").onChange((value) => this.passphrase = value);
      text.inputEl.type = "password";
      text.inputEl.addEventListener("keypress", (e) => {
        if (e.key === "Enter" && !this.isNewPassphrase) {
          this.submit();
        }
      });
    });
    if (this.isNewPassphrase) {
      new import_obsidian5.Setting(contentEl).setName("Confirm Passphrase").setDesc("Re-enter to confirm").addText((text) => {
        text.setPlaceholder("Confirm passphrase").onChange((value) => this.confirmPassphrase = value);
        text.inputEl.type = "password";
        text.inputEl.addEventListener("keypress", (e) => {
          if (e.key === "Enter") {
            this.submit();
          }
        });
      });
    }
    if (this.isNewPassphrase) {
      const tipsDiv = contentEl.createDiv("passphrase-tips");
      tipsDiv.style.padding = "15px";
      tipsDiv.style.marginTop = "20px";
      tipsDiv.style.backgroundColor = "var(--background-secondary)";
      tipsDiv.style.borderRadius = "8px";
      tipsDiv.createEl("strong", { text: "\u{1F4A1} Security Tips:" });
      const tipsList = tipsDiv.createEl("ul");
      tipsList.style.marginTop = "10px";
      tipsList.style.marginLeft = "20px";
      const tips = [
        "Use a unique passphrase (don't reuse your vault password)",
        "Store it in a password manager",
        "If forgotten, you'll need to re-enter all API keys"
      ];
      tips.forEach((tip) => {
        tipsList.createEl("li", { text: tip });
      });
    }
    const buttonContainer = contentEl.createDiv("button-container");
    buttonContainer.style.display = "flex";
    buttonContainer.style.justifyContent = "flex-end";
    buttonContainer.style.gap = "10px";
    buttonContainer.style.marginTop = "20px";
    new import_obsidian5.Setting(buttonContainer).addButton(
      (btn) => btn.setButtonText("Cancel").onClick(() => {
        this.onSubmit(null);
        this.close();
      })
    ).addButton(
      (btn) => btn.setButtonText(this.isNewPassphrase ? "Create" : "Unlock").setCta().onClick(() => this.submit())
    );
  }
  submit() {
    if (this.passphrase.length < 8) {
      new import_obsidian5.Notice("\u26A0\uFE0F Passphrase must be at least 8 characters");
      return;
    }
    if (this.isNewPassphrase) {
      if (this.passphrase !== this.confirmPassphrase) {
        new import_obsidian5.Notice("\u26A0\uFE0F Passphrases do not match");
        return;
      }
      if (this.passphrase.length < 12) {
        new import_obsidian5.Notice("\u26A0\uFE0F Warning: Passphrase should be at least 12 characters for better security");
      }
    }
    this.onSubmit(this.passphrase);
    this.close();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
    this.passphrase = "";
    this.confirmPassphrase = "";
  }
};
var MigrationModal = class extends import_obsidian5.Modal {
  constructor(app, insecureCount, onMigrate) {
    super(app);
    this.insecureCount = insecureCount;
    this.onMigrate = onMigrate;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u26A0\uFE0F Security Warning" });
    const warningDiv = contentEl.createDiv("security-warning");
    warningDiv.style.padding = "15px";
    warningDiv.style.marginBottom = "20px";
    warningDiv.style.backgroundColor = "var(--background-modifier-error)";
    warningDiv.style.borderRadius = "8px";
    warningDiv.style.border = "2px solid var(--text-error)";
    warningDiv.createEl("p", {
      text: `\u26A0\uFE0F Found ${this.insecureCount} API key(s) stored in PLAINTEXT!`
    }).style.fontWeight = "bold";
    warningDiv.createEl("p", {
      text: "Anyone with access to your file system can read these keys. This is a serious security risk."
    });
    const infoDiv = contentEl.createDiv("migration-info");
    infoDiv.style.padding = "15px";
    infoDiv.style.marginBottom = "20px";
    infoDiv.style.backgroundColor = "var(--background-secondary)";
    infoDiv.style.borderRadius = "8px";
    infoDiv.createEl("h3", { text: "\u{1F510} Migrate to Encrypted Storage" });
    infoDiv.createEl("p", {
      text: "QuizDex v2.0 can encrypt your API keys with AES-256-GCM encryption."
    });
    const stepsList = infoDiv.createEl("ol");
    stepsList.style.marginLeft = "20px";
    stepsList.style.marginTop = "10px";
    [
      "Create a secure passphrase",
      "All API keys will be encrypted automatically",
      "Plaintext keys will be removed from settings",
      "You'll need the passphrase to use the plugin"
    ].forEach((step) => {
      stepsList.createEl("li", { text: step });
    });
    const buttonContainer = contentEl.createDiv("button-container");
    buttonContainer.style.display = "flex";
    buttonContainer.style.justifyContent = "space-between";
    buttonContainer.style.marginTop = "20px";
    new import_obsidian5.Setting(buttonContainer).addButton(
      (btn) => btn.setButtonText("Remind Me Later").onClick(() => {
        new import_obsidian5.Notice("\u26A0\uFE0F Your API keys remain UNENCRYPTED. Please migrate soon!");
        this.close();
      })
    ).addButton(
      (btn) => btn.setButtonText("Migrate Now").setCta().onClick(async () => {
        this.close();
        new PassphraseModal(this.app, async (passphrase) => {
          if (passphrase) {
            await this.onMigrate(passphrase);
          }
        }, true).open();
      })
    );
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/ui/SettingsTab.ts
var import_obsidian6 = require("obsidian");
var QuizDexSettingTab = class extends import_obsidian6.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  async display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h1", { text: "QuizDex Settings" });
    await this.renderSecuritySection(containerEl);
    await this.renderProvidersSection(containerEl);
    this.renderQuizSettings(containerEl);
  }
  /**
   * Render security section with audit and passphrase management
   */
  async renderSecuritySection(containerEl) {
    containerEl.createEl("h2", { text: "\u{1F510} Security" });
    const audit = await this.plugin.credentialManager.auditSecurity();
    const auditContainer = containerEl.createDiv("security-audit-container");
    auditContainer.style.padding = "15px";
    auditContainer.style.marginBottom = "20px";
    auditContainer.style.borderRadius = "8px";
    auditContainer.style.border = "2px solid";
    if (audit.insecure > 0) {
      auditContainer.style.backgroundColor = "var(--background-modifier-error)";
      auditContainer.style.borderColor = "var(--text-error)";
      auditContainer.createEl("h3", {
        text: `\u26A0\uFE0F Security Warning`,
        attr: { style: "margin: 0 0 10px 0; color: var(--text-error);" }
      });
      auditContainer.createEl("p", {
        text: `${audit.insecure} API key(s) stored in PLAINTEXT!`,
        attr: { style: "margin: 5px 0; font-weight: bold;" }
      });
      auditContainer.createEl("p", {
        text: "Anyone with access to your vault can read these keys.",
        attr: { style: "margin: 5px 0;" }
      });
      const migrateBtn = auditContainer.createEl("button", {
        text: "Migrate to Encrypted Storage Now",
        cls: "mod-cta"
      });
      migrateBtn.style.marginTop = "10px";
      migrateBtn.addEventListener("click", async () => {
        await this.promptMigration();
      });
    } else if (audit.secure > 0) {
      auditContainer.style.backgroundColor = "var(--background-modifier-success)";
      auditContainer.style.borderColor = "var(--color-green)";
      auditContainer.createEl("h3", {
        text: "\u2705 All API Keys Encrypted",
        attr: { style: "margin: 0 0 10px 0; color: var(--color-green);" }
      });
      auditContainer.createEl("p", {
        text: `${audit.secure} credential(s) protected with AES-256-GCM encryption`,
        attr: { style: "margin: 5px 0;" }
      });
      if (audit.providers.length > 0) {
        auditContainer.createEl("p", {
          text: `Providers: ${audit.providers.map((p) => ProviderFactory.getProviderDisplayName(p)).join(", ")}`,
          attr: { style: "margin: 5px 0; font-size: 0.9em; color: var(--text-muted);" }
        });
      }
    } else {
      auditContainer.style.backgroundColor = "var(--background-secondary)";
      auditContainer.style.borderColor = "var(--background-modifier-border)";
      auditContainer.createEl("h3", {
        text: "\u2139\uFE0F No API Keys Configured",
        attr: { style: "margin: 0 0 10px 0;" }
      });
      auditContainer.createEl("p", {
        text: "Add API keys below to use cloud AI providers. All keys will be encrypted automatically.",
        attr: { style: "margin: 5px 0;" }
      });
    }
    new import_obsidian6.Setting(containerEl).setName("Change Encryption Passphrase").setDesc("Update the passphrase used to encrypt your API keys").addButton(
      (btn) => btn.setButtonText("Change Passphrase").onClick(async () => {
        await this.changePassphrase();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Clear All Encrypted Credentials").setDesc("\u26A0\uFE0F Warning: This will permanently delete all encrypted API keys").addButton(
      (btn) => btn.setButtonText("Clear All").setWarning().onClick(async () => {
        await this.clearAllCredentials();
      })
    );
  }
  /**
   * Render AI providers section
   */
  async renderProvidersSection(containerEl) {
    containerEl.createEl("h2", { text: "\u{1F916} AI Providers" });
    containerEl.createEl("p", {
      text: "Configure AI providers for quiz generation. API keys are encrypted with AES-256-GCM.",
      cls: "setting-item-description"
    });
    new import_obsidian6.Setting(containerEl).setName("Active Provider").setDesc("Default AI provider for quiz generation").addDropdown((dropdown) => {
      const providers2 = ProviderFactory.getSupportedProviders();
      providers2.forEach((provider) => {
        dropdown.addOption(provider, ProviderFactory.getProviderDisplayName(provider));
      });
      dropdown.setValue(this.plugin.settings.provider);
      dropdown.onChange(async (value) => {
        this.plugin.settings.provider = value;
        await this.plugin.saveSettings();
      });
    });
    const providers = ProviderFactory.getSupportedProviders();
    for (const provider of providers) {
      await this.renderProviderSettings(containerEl, provider);
    }
  }
  /**
   * Render settings for individual provider
   */
  async renderProviderSettings(containerEl, provider) {
    const displayName = ProviderFactory.getProviderDisplayName(provider);
    const requiresKey = ProviderFactory.requiresApiKey(provider);
    containerEl.createEl("h3", { text: displayName });
    new import_obsidian6.Setting(containerEl).setName(`${displayName} Base URL`).setDesc(provider === "ollama" ? "Local Ollama server endpoint" : "API endpoint URL").addText((text) => {
      const key = `${provider}BaseURL`;
      text.setPlaceholder(provider === "ollama" ? "http://localhost:11434" : "https://api.example.com").setValue(this.plugin.settings[key] || "").onChange(async (value) => {
        this.plugin.settings[key] = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian6.Setting(containerEl).setName(`${displayName} Model`).setDesc("Model to use for quiz generation").addText((text) => {
      const key = `${provider}TextGenModel`;
      text.setPlaceholder(provider === "ollama" ? "llama3.1:8b" : "model-name").setValue(this.plugin.settings[key] || "").onChange(async (value) => {
        this.plugin.settings[key] = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian6.Setting(containerEl).setName(`Test ${displayName} Connection`).setDesc(provider === "ollama" ? "Verify local Ollama server is running" : "Verify API key and connection").addButton(
      (btn) => btn.setButtonText("Test Connection").onClick(async () => {
        await this.testProviderConnection(provider, displayName);
      })
    );
    if (requiresKey) {
      const hasKey = await this.plugin.credentialManager.hasCredential(provider);
      new import_obsidian6.Setting(containerEl).setName(`${displayName} API Key`).setDesc(hasKey ? "\u2705 Encrypted key stored" : "Enter API key (will be encrypted)").addText((text) => {
        text.setPlaceholder(hasKey ? "\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022" : "Enter API key");
        text.inputEl.type = "password";
        return text;
      }).addButton(
        (btn) => btn.setButtonText(hasKey ? "Update" : "Save").onClick(async () => {
          await this.saveApiKey(provider, displayName);
        })
      ).addButton((btn) => {
        if (hasKey) {
          btn.setButtonText("Remove").setWarning().onClick(async () => {
            await this.plugin.credentialManager.removeCredential(provider);
            this.display();
          });
        }
      });
    }
  }
  /**
   * Render quiz settings section
   */
  renderQuizSettings(containerEl) {
    containerEl.createEl("h2", { text: "\u{1F4DD} Quiz Settings" });
    new import_obsidian6.Setting(containerEl).setName("Default Number of Questions").setDesc("Default number of questions to generate").addSlider(
      (slider) => slider.setLimits(5, 50, 5).setValue(this.plugin.settings.defaultQuestions).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.defaultQuestions = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Default Difficulty").setDesc("Default difficulty level").addDropdown(
      (dropdown) => dropdown.addOption("easy", "Easy").addOption("medium", "Medium").addOption("hard", "Hard").setValue(this.plugin.settings.defaultDifficulty).onChange(async (value) => {
        this.plugin.settings.defaultDifficulty = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Include Multiple Choice").setDesc("Generate multiple choice questions").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.includeMultipleChoice).onChange(async (value) => {
        this.plugin.settings.includeMultipleChoice = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Include True/False").setDesc("Generate true/false questions").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.includeTrueFalse).onChange(async (value) => {
        this.plugin.settings.includeTrueFalse = value;
        await this.plugin.saveSettings();
      })
    );
  }
  /**
   * Save API key with encryption
   */
  async saveApiKey(provider, displayName) {
    const input = document.querySelector(`input[type="password"][placeholder*="${displayName}"], input[type="password"][placeholder*="Enter API key"]`);
    if (!input || !input.value.trim()) {
      new import_obsidian6.Notice("\u26A0\uFE0F Please enter an API key");
      return;
    }
    const apiKey = input.value.trim();
    new PassphraseModal(
      this.app,
      async (passphrase) => {
        if (!passphrase)
          return;
        const initialized = await this.plugin.credentialManager.initialize(passphrase);
        if (!initialized) {
          new import_obsidian6.Notice("\u274C Invalid passphrase");
          return;
        }
        const success = await this.plugin.credentialManager.setCredential(
          provider,
          apiKey,
          passphrase
        );
        if (success) {
          input.value = "";
          this.display();
          await this.plugin.initializeProviders();
        }
      },
      !await this.plugin.credentialManager.hasCredential(provider)
    ).open();
  }
  /**
   * Test provider connection
   */
  async testProviderConnection(provider, displayName) {
    const providerInstance = this.plugin.orchestrator.getProvider(provider);
    if (!providerInstance) {
      new import_obsidian6.Notice(`\u274C ${displayName} not configured`);
      return;
    }
    new import_obsidian6.Notice(`\u23F3 Testing ${displayName} connection...`);
    const health = await providerInstance.healthCheck();
    if (health.healthy) {
      new import_obsidian6.Notice(`\u2705 ${displayName} connection successful! (${health.latency}ms)`);
    } else {
      new import_obsidian6.Notice(`\u274C ${displayName} connection failed: ${health.message || "Unknown error"}`);
    }
  }
  /**
   * Prompt migration from plaintext to encrypted
   */
  async promptMigration() {
    new PassphraseModal(
      this.app,
      async (passphrase) => {
        if (!passphrase)
          return;
        const initialized = await this.plugin.credentialManager.initialize(passphrase);
        if (!initialized) {
          new import_obsidian6.Notice("\u274C Failed to initialize encryption");
          return;
        }
        const success = await this.plugin.credentialManager.migrateToEncrypted(
          passphrase,
          this.plugin.settings
        );
        if (success) {
          delete this.plugin.settings.openAIApiKey;
          delete this.plugin.settings.anthropicApiKey;
          delete this.plugin.settings.googleApiKey;
          delete this.plugin.settings.perplexityApiKey;
          delete this.plugin.settings.mistralApiKey;
          delete this.plugin.settings.cohereApiKey;
          this.plugin.settings.hasMigrated = true;
          await this.plugin.saveSettings();
          this.display();
        }
      },
      true
    ).open();
  }
  /**
   * Change encryption passphrase
   */
  async changePassphrase() {
    new import_obsidian6.Notice("\u26A0\uFE0F Changing passphrase is not yet implemented. You can clear all credentials and re-enter them with a new passphrase.");
  }
  /**
   * Clear all encrypted credentials
   */
  async clearAllCredentials() {
    const confirmed = confirm(
      "\u26A0\uFE0F WARNING: This will permanently delete all encrypted API keys!\n\nYou will need to re-enter all API keys.\n\nAre you sure you want to continue?"
    );
    if (confirmed) {
      await this.plugin.credentialManager.clearAll();
      this.display();
    }
  }
};

// src/main.ts
var DEFAULT_SETTINGS = {
  provider: "ollama",
  ollamaBaseURL: "http://localhost:11434",
  openAIBaseURL: "https://api.openai.com/v1",
  anthropicBaseURL: "https://api.anthropic.com",
  googleBaseURL: "https://generativelanguage.googleapis.com",
  perplexityBaseURL: "https://api.perplexity.ai",
  mistralBaseURL: "https://api.mistral.ai",
  cohereBaseURL: "https://api.cohere.com",
  ollamaTextGenModel: "llama3.1:8b",
  openAITextGenModel: "gpt-4o-mini",
  anthropicTextGenModel: "claude-3-haiku-20240307",
  googleTextGenModel: "gemini-1.5-flash",
  perplexityTextGenModel: "llama-3.1-sonar-small-128k-chat",
  mistralTextGenModel: "open-mistral-nemo",
  cohereTextGenModel: "command-r-08-2024",
  defaultQuestions: 10,
  defaultDifficulty: "medium",
  includeMultipleChoice: true,
  includeTrueFalse: true
};
var QuizDexPlugin = class extends import_obsidian7.Plugin {
  constructor() {
    super(...arguments);
    this.passphraseCache = null;
  }
  async onload() {
    console.log("Loading QuizDex v2.0...");
    await this.loadSettings();
    this.credentialManager = new CredentialManager(this);
    this.orchestrator = new AIProviderOrchestrator();
    await this.checkAndMigrate();
    await this.ensurePassphraseUnlocked();
    await this.initializeProviders();
    const ribbonIconEl = this.addRibbonIcon("graduation-cap", "QuizDex: Generate Quiz from Active Note", () => {
      this.generateQuizFromActiveFile();
    });
    ribbonIconEl.addClass("quizdex-ribbon-icon");
    ribbonIconEl.setAttribute("aria-label", "QuizDex: Generate Quiz");
    this.addCommand({
      id: "generate-quiz",
      name: "Generate Quiz from Notes",
      callback: () => this.generateQuizCommand()
    });
    this.addCommand({
      id: "generate-quiz-active",
      name: "Generate Quiz from Active Note",
      callback: () => this.generateQuizFromActiveFile()
    });
    this.addCommand({
      id: "security-audit",
      name: "Run Security Audit",
      callback: () => this.runSecurityAudit()
    });
    this.addCommand({
      id: "provider-status",
      name: "Show AI Provider Status",
      callback: () => this.showProviderStatus()
    });
    this.addSettingTab(new QuizDexSettingTab(this.app, this));
    console.log("\u2705 QuizDex v2.0 loaded successfully");
  }
  onunload() {
    this.credentialManager.destroy();
    this.orchestrator.destroy();
    this.passphraseCache = null;
    console.log("QuizDex unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * Check for insecure API keys and prompt migration
   */
  async checkAndMigrate() {
    if (this.settings.hasMigrated) {
      return;
    }
    const audit = await this.credentialManager.auditSecurity();
    if (audit.insecure > 0) {
      new import_obsidian7.Notice(`\u26A0\uFE0F Found ${audit.insecure} unencrypted API key(s)`, 5e3);
      setTimeout(() => {
        new MigrationModal(
          this.app,
          audit.insecure,
          async (passphrase) => {
            if (passphrase) {
              await this.performMigration(passphrase);
            }
          }
        ).open();
      }, 2e3);
    }
  }
  /**
   * Perform migration from plaintext to encrypted storage
   */
  async performMigration(passphrase) {
    try {
      const initialized = await this.credentialManager.initialize(passphrase);
      if (!initialized) {
        new import_obsidian7.Notice("\u274C Failed to initialize encryption");
        return;
      }
      const success = await this.credentialManager.migrateToEncrypted(
        passphrase,
        this.settings
      );
      if (success) {
        delete this.settings.openAIApiKey;
        delete this.settings.anthropicApiKey;
        delete this.settings.googleApiKey;
        delete this.settings.perplexityApiKey;
        delete this.settings.mistralApiKey;
        delete this.settings.cohereApiKey;
        this.settings.hasMigrated = true;
        this.settings.passphraseSet = true;
        await this.saveSettings();
        this.passphraseCache = passphrase;
        new import_obsidian7.Notice("\u2705 Migration complete! Your API keys are now encrypted.");
        await this.initializeProviders();
      }
    } catch (error) {
      console.error("Migration failed:", error);
      new import_obsidian7.Notice("\u274C Migration failed. Please try again.");
    }
  }
  /**
   * Ensure user has unlocked encrypted credentials
   */
  async ensurePassphraseUnlocked() {
    const audit = await this.credentialManager.auditSecurity();
    if (audit.secure === 0) {
      return true;
    }
    if (this.passphraseCache) {
      const initialized = await this.credentialManager.initialize(this.passphraseCache);
      if (initialized) {
        return true;
      }
    }
    return new Promise((resolve) => {
      new PassphraseModal(
        this.app,
        async (passphrase) => {
          if (passphrase) {
            const initialized = await this.credentialManager.initialize(passphrase);
            if (initialized) {
              this.passphraseCache = passphrase;
              resolve(true);
            } else {
              new import_obsidian7.Notice("\u274C Invalid passphrase");
              resolve(false);
            }
          } else {
            resolve(false);
          }
        },
        false
      ).open();
    });
  }
  /**
   * Initialize all AI providers
   */
  async initializeProviders() {
    await ProviderFactory.initializeAll(
      this.orchestrator,
      async (provider) => this.getProviderConfig(provider)
    );
    const registeredProviders = this.orchestrator.listProviders();
    console.log(`\u2705 Registered ${registeredProviders.length} AI providers:`, registeredProviders);
  }
  /**
   * Get configuration for a specific provider
   */
  async getProviderConfig(provider) {
    const baseURLKey = `${provider}BaseURL`;
    const modelKey = `${provider}TextGenModel`;
    const baseURL = this.settings[baseURLKey];
    const model = this.settings[modelKey];
    if (!baseURL || !model) {
      return null;
    }
    let apiKey;
    if (ProviderFactory.requiresApiKey(provider)) {
      apiKey = await this.credentialManager.getCredential(provider) || void 0;
    }
    return {
      baseURL,
      model,
      apiKey,
      timeout: 6e4,
      maxRetries: 3
    };
  }
  /**
   * Generate quiz from active file (ribbon icon / command)
   */
  async generateQuizFromActiveFile() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian7.Notice("\u26A0\uFE0F No active file open");
      return;
    }
    const unlocked = await this.ensurePassphraseUnlocked();
    if (!unlocked) {
      new import_obsidian7.Notice("\u274C Cannot generate quiz without unlocking encrypted credentials");
      return;
    }
    new import_obsidian7.Notice(`\u{1F3AE} Generating quiz from "${activeFile.basename}"...`);
  }
  /**
   * Generate quiz command (select notes)
   */
  async generateQuizCommand() {
    const unlocked = await this.ensurePassphraseUnlocked();
    if (!unlocked) {
      new import_obsidian7.Notice("\u274C Cannot generate quiz without unlocking encrypted credentials");
      return;
    }
    new import_obsidian7.Notice("\u{1F3AE} Quiz generation from selected notes coming soon!");
  }
  /**
   * Run security audit command
   */
  async runSecurityAudit() {
    const audit = await this.credentialManager.auditSecurity();
    const message = [
      "\u{1F510} Security Audit Results:",
      ``,
      `\u2705 Encrypted API keys: ${audit.secure}`,
      `\u26A0\uFE0F Plaintext API keys: ${audit.insecure}`,
      ``,
      audit.secure > 0 ? `Providers with encrypted keys: ${audit.providers.join(", ")}` : "",
      audit.insecure > 0 ? `\u26A0\uFE0F Please migrate to encrypted storage!` : ""
    ].filter(Boolean).join("\n");
    new import_obsidian7.Notice(message, 1e4);
    console.log("Security Audit:", audit);
  }
  /**
   * Show provider status command
   */
  async showProviderStatus() {
    const status = this.orchestrator.getCircuitBreakerStatus();
    const providers = this.orchestrator.listProviders();
    const statusMessages = [];
    statusMessages.push("\u{1F50C} AI Provider Status:\n");
    if (providers.length === 0) {
      statusMessages.push("\u26A0\uFE0F No providers registered");
    } else {
      for (const provider of providers) {
        const breaker = status.get(provider);
        const stateIcon = {
          "closed": "\u2705",
          "open": "\u274C",
          "half-open": "\u26A0\uFE0F"
        }[(breaker == null ? void 0 : breaker.state) || "closed"];
        const failures = (breaker == null ? void 0 : breaker.failures) || 0;
        statusMessages.push(`${stateIcon} ${provider}: ${(breaker == null ? void 0 : breaker.state) || "unknown"} (${failures} failures)`);
      }
    }
    new import_obsidian7.Notice(statusMessages.join("\n"), 8e3);
    console.log("Provider Status:", Object.fromEntries(status));
  }
};
